# Generated by Django 4.1.5 on 2023-01-23 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptName', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipType', models.CharField(max_length=50)),
                ('addedDate', models.DateField(default=None)),
            ],
            options={
                'ordering': ['-addedDate'],
            },
        ),
        migrations.CreateModel(
            name='SysAdmin',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(blank=True, max_length=10)),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EquipDescr',
            fields=[
                ('equipID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ITapp.resource', unique=True)),
                ('specificDescr', models.TextField(blank=True, null=True)),
                ('genericDescr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MagStaff',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('phoneNo', models.CharField(blank=True, max_length=10)),
                ('auth_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ITapp.sysadmin')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ITapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownDept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ITapp.department')),
                ('ownRID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ITapp.resource')),
            ],
            options={
                'unique_together': {('ownDept', 'ownRID')},
            },
        ),
    ]
