# Generated by Django 4.1.5 on 2023-01-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owns',
            name='ownRID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ITapp.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='equipType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
