# Generated by Django 4.1.5 on 2023-02-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0002_alter_owns_ownrid_alter_resource_equiptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='condition',
            field=models.BooleanField(default=True),
        ),
    ]
